const {chromium}=require('playwright');const assert=require('node:assert/strict');
async function settled(page){await page.waitForFunction(()=>window.campaignReady && document.body.dataset.busy==='false');}
async function click(page,selector){await page.locator(selector).click();await settled(page);}
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH || '/usr/bin/chromium',args:['--no-sandbox']});
 try{
  const page=await browser.newPage({viewport:{width:1440,height:900},reducedMotion:'reduce'});const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(process.env.APP_URL || 'http://127.0.0.1:3003');await settled(page);
  await page.locator('#navProfile').click();await page.locator('#businessName').fill('Neighborhood Pups');await page.locator('#businessAudience').fill('Brooklyn puppy parents');await page.locator('#businessTagline').fill('Gentle care. Happy tails.');await page.locator('#businessBooking').fill('https://example.com/book');await page.locator('#profileForm .save-button').click();
  await page.locator('#topic').fill('Three Saturday appointments are open.');await click(page,'.generate-button');
  const original=await page.locator('#draftCopy').inputValue();assert.match(original,/Neighborhood Pups/);assert.match(original,/Message our team/);assert.doesNotMatch(original,/Book here/);
  await click(page,'#regenerateButton');const second=await page.locator('#draftCopy').inputValue();assert.notEqual(second,original);assert.match(second,/Brooklyn puppy parents/);
  await click(page,'#regenerateButton');assert.equal(await page.locator('#draftCopy').inputValue(),original);assert.equal(await page.locator('#libraryCount').textContent(),'1');assert.equal(await page.locator('#versionSelect option').count(),2);
  await page.locator('#draftCopy').fill('Edited customer-facing copy.');await click(page,'#saveVersionButton');assert.equal(await page.locator('#libraryCount').textContent(),'1');assert.equal(await page.locator('#versionSelect option').count(),3);
  await click(page,'#saveVersionButton');assert.equal(await page.locator('#versionSelect option').count(),3);
  await click(page,'#navHistory');await page.getByRole('button',{name:'Archive',exact:true}).click();await settled(page);assert.equal(await page.locator('#libraryCount').textContent(),'0');await click(page,'#undoHistory');assert.equal(await page.locator('#libraryCount').textContent(),'1');await page.locator('.history-item').first().click();
  await page.locator('#topic').fill('An unfinished brief');await page.reload();await settled(page);assert.equal(await page.locator('#topic').inputValue(),'An unfinished brief');assert.equal(await page.locator('#draftCopy').inputValue(),'Edited customer-facing copy.');
  await page.locator('[data-tool="campaign"]').click();assert.equal(await page.locator('#topic').inputValue(),'');assert(await page.locator('#draft').evaluate(e=>e.classList.contains('hidden')));
  await page.locator('#topic').fill('Gentle first grooms for local puppies.');await click(page,'.generate-button');assert.equal(await page.locator('#assetSelect option').count(),10);
  await page.locator('#assetSelect').selectOption('Video 1 script: Preparation');const video1=await page.locator('#draftCopy').inputValue();await page.locator('#assetSelect').selectOption('Video 2 script: Trust');assert.notEqual(await page.locator('#draftCopy').inputValue(),video1);await page.locator('#assetSelect').selectOption('Seven-day plan');assert.match(await page.locator('#draftCopy').inputValue(),/SUNDAY/);
  const downloaded=page.waitForEvent('download');await page.locator('#downloadButton').click();assert.equal((await downloaded).suggestedFilename(),'marketing-draft.txt');
  await page.locator('[data-view="care"]').click();assert.equal(await page.locator('#topic').inputValue(),'');assert(await page.locator('#marketingSettings').evaluate(e=>e.hidden));
  await page.locator('#topic').fill('My dog was injured and I was not told.');await page.locator('#reviewSentiment').selectOption('Negative');await click(page,'.generate-button');assert(await page.locator('#reviewAlert').isVisible());assert.match(await page.locator('#draftCopy').inputValue(),/concerned/);assert.doesNotMatch(await page.locator('#draftCopy').inputValue(),/did not meet your expectations/);
  await page.locator('[data-tool="followup"]').click();await page.locator('.quick-prompts button').first().click();await click(page,'.generate-button');assert.match(await page.locator('#draftCopy').inputValue(),/How is your pup/);assert.doesNotMatch(await page.locator('#draftCopy').inputValue(),/Check in with a customer|book your/);
  await page.locator('#topic').fill('Check in with a customer after their first groom');const prior=await page.locator('#draftCopy').inputValue();await click(page,'.generate-button');assert.equal(await page.locator('#draftCopy').inputValue(),prior);
  await click(page,'#navHistory');await page.locator('.history-item').last().click();assert.equal(await page.locator('#topic').inputValue(),'Three Saturday appointments are open.');assert.equal(await page.locator('#draftCopy').inputValue(),'Edited customer-facing copy.');
  const entries=await page.evaluate(async()=>{const session=await (await fetch('/api/session')).json();return (await (await fetch('/api/campaigns?workspaceId='+session.value.workspaces[0].id)).json()).value.filter(c=>!c.archived);});assert.equal(entries.length,4);
  await page.locator('[data-view="results"]').click();assert.match(await page.locator('#resultsList').textContent(),/No outcomes/);assert.doesNotMatch(await page.locator('#resultsMetrics').textContent(),/\$0/);
  await page.locator('#addResult').click();await page.locator('#resultCampaign').fill('Saturday openings');await page.locator('#resultSource').fill('Facebook');await page.locator('#resultDate').fill('2026-10-08');await page.locator('#resultInquiries').fill('10');await page.locator('#resultBookings').fill('3');await page.locator('#resultBooked').fill('240');await page.locator('#resultRevenue').fill('160');await page.locator('#resultSpend').fill('20');await page.locator('#resultForm .save-button').click();assert.match(await page.locator('#resultsMetrics').textContent(),/\$140\.00/);
  await page.locator('.result-row button').first().click();await page.locator('#resultRevenue').fill('200');await page.locator('#resultForm .save-button').click();assert.equal(await page.locator('.result-row').count(),1);assert.match(await page.locator('#resultsMetrics').textContent(),/\$180\.00/);
  await page.getByRole('button',{name:'Remove record',exact:true}).click();assert.equal(await page.locator('.result-row').count(),0);await page.locator('#undoResult').click();assert.equal(await page.locator('.result-row').count(),1);
  await page.locator('#addResult').click();await page.locator('#resultCampaign').fill('Saturday openings');await page.locator('#resultSource').fill('Facebook');await page.locator('#resultDate').fill('2026-10-08');await page.locator('#resultForm .save-button').click();assert(await page.locator('#resultDialog').isVisible());assert.equal(await page.locator('.result-row').count(),1);await page.locator('#closeResult').click();
  await page.locator('#currency').selectOption('GBP');assert.match(await page.locator('#resultsList').textContent(),/No outcomes/);await page.locator('#currency').selectOption('USD');assert.equal(await page.locator('.result-row').count(),1);
  const csv=page.waitForEvent('download');await page.locator('#exportResults').click();assert.equal((await csv).suggestedFilename(),'marketing-results.csv');
  await page.reload();await settled(page);await page.locator('[data-view="results"]').click();assert.match(await page.locator('#resultsMetrics').textContent(),/\$180\.00/);
  await page.locator('[data-view="create"]').click();await page.locator('#topic').fill('<img src=x onerror="window.injected=true">');await click(page,'.generate-button');await click(page,'#navHistory');assert.equal(await page.locator('#historyList img').count(),0);await page.keyboard.press('Escape');
  for(const width of [320,390,680,768,1024,1440]){await page.setViewportSize({width,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`overflow ${width}`);await click(page,'#navHistory');const bounds=await page.locator('#historyDrawer').boundingBox();assert(bounds.x>=0 && bounds.x+bounds.width<=width+1);await page.keyboard.press('Escape');}
  await page.evaluate(()=>{localStorage.setItem('ff-profile','invalid');localStorage.setItem('ff-working','{}');localStorage.setItem('ff-history',JSON.stringify([{tool:'pack',topic:'Old campaign',copy:'Original legacy pack',date:'2026-10-01T12:00:00Z'}]));});await page.reload();await settled(page);await click(page,'#navHistory');await page.locator('.history-item').first().click();assert.equal(await page.locator('#draftCopy').inputValue(),'Original legacy pack');assert.deepEqual(errors,[]);
  console.log('PASS: grouped alternatives/versions, inline edits, recovered briefs, independent workflows, campaign assets, customer care, legacy history, safe rendering, exports, manual totals/editing/currency separation, persistence, and six responsive widths.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
