const {chromium}=require('playwright');const assert=require('node:assert/strict');
const settled=page=>page.waitForFunction(()=>window.campaignReady && document.body.dataset.busy==='false');
async function click(page,selector){await page.locator(selector).click();await settled(page);}
async function list(page){return page.evaluate(async()=>{const session=await(await fetch('/api/session')).json();return (await(await fetch('/api/campaigns?workspaceId='+session.value.workspaces[0].id)).json()).value;});}
const failure={ok:false,error:{code:'PERSISTENCE_ERROR',message:'Injected failure; your edits are kept.',retryable:true}};
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox']});try{
 const context=await browser.newContext();const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{localStorage.setItem('ff-working','{"social":null}');localStorage.setItem('ff-history','[{"tool":"social","topic":"Bad history","copy":"Saved copy","versions":null},null]');});
 await page.goto(process.env.APP_URL);await settled(page);assert(await page.locator('#migrationNotice').isVisible());assert.match(await page.locator('#migrationMessage').textContent(),/2 rejected/);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('ff-working')).social),null);
 await page.locator('#topic').fill('Transactional browser test appointments are available.');let createRequests=[];let loseCreate=true;
 await page.route('**/api/campaigns/create',async route=>{createRequests.push(route.request().postDataJSON());if(loseCreate){loseCreate=false;await route.fetch();await route.fulfill({status:503,json:failure});}else await route.continue();});
 const before=(await list(page)).length;await click(page,'.generate-button');assert.equal(await page.locator('#versionSelect option').count(),0);assert.equal((await list(page)).length,before+1);await click(page,'.generate-button');assert.equal((await list(page)).length,before+1);assert.equal(createRequests.length,2);assert.equal(createRequests[0].idempotencyKey,createRequests[1].idempotencyKey);assert.equal(await page.locator('#versionSelect option').count(),1);
 const c=(await list(page)).find(c=>c.brief.topic.startsWith('Transactional browser'));assert(c);await page.unroute('**/api/campaigns/create');
 // Failed save must leave the visible saved-version list unchanged, and preserve edited text.
 let failSave=true;const saveRequests=[];await page.route('**/api/campaigns/saveVersion',async route=>{saveRequests.push(route.request().postDataJSON());if(failSave){failSave=false;await route.fulfill({status:503,json:failure});}else await route.continue();});
 await page.locator('#draftCopy').fill('An edited version that initially fails.');await click(page,'#saveVersionButton');assert.equal(await page.locator('#versionSelect option').count(),1);assert.equal(await page.locator('#draftCopy').inputValue(),'An edited version that initially fails.');assert.equal((await list(page)).find(x=>x.id===c.id).versions.length,1);await click(page,'#saveVersionButton');assert.equal(await page.locator('#versionSelect option').count(),2);assert.equal(saveRequests[0].idempotencyKey,saveRequests[1].idempotencyKey);await page.unroute('**/api/campaigns/saveVersion');
 // Two independent tabs open the same authoritative revision. One wins; the other retains its edit.
 const other=await context.newPage();other.on('pageerror',e=>errors.push(e.message));await other.goto(process.env.APP_URL);await settled(other);await click(other,'#navHistory');await other.locator('.history-item').filter({hasText:'Transactional browser test'}).click();
 await page.locator('#draftCopy').fill('First tab committed.');await click(page,'#saveVersionButton');await other.locator('#draftCopy').fill('Second tab must not overwrite.');await click(other,'#saveVersionButton');assert(await other.locator('#conflictNotice').isVisible());assert.equal(await other.locator('#draftCopy').inputValue(),'Second tab must not overwrite.');const committed=(await list(page)).find(x=>x.id===c.id);assert.equal(committed.versions.length,3);assert.equal(committed.versions.at(-1).assets.message,'First tab committed.');
 // Separate draft briefs stay per tab, including across reload.
 await page.locator('#topic').fill('Unfinished first-tab brief');await other.locator('#topic').fill('Unfinished second-tab brief');await page.reload();await settled(page);await other.reload();await settled(other);assert.equal(await page.locator('#topic').inputValue(),'Unfinished first-tab brief');assert.equal(await other.locator('#topic').inputValue(),'Unfinished second-tab brief');
 // Bob sees neither Alice campaigns nor Alice's per-workspace scratch. Server denies forged workspace.
 await page.locator('#identitySelect').selectOption('bob');await settled(page);assert.equal(await page.locator('#libraryCount').textContent(),'0');assert.equal(await page.locator('#topic').inputValue(),'');const denied=await page.evaluate(async()=>({status:(await fetch('/api/campaigns?workspaceId=workspace-alice')).status}));assert.equal(denied.status,403);assert(await page.locator('#migrationNotice').isHidden());await page.locator('#identitySelect').selectOption('alice');await settled(page);assert.equal(await page.locator('#topic').inputValue(),'Unfinished first-tab brief');
 await page.locator('#topic').fill('Reopened template alternatives remain distinct.');await click(page,'.generate-button');const templateBefore=await page.locator('#draftCopy').inputValue();await click(page,'#navHistory');await page.locator('.history-item').filter({hasText:'Reopened template alternatives'}).click();await click(page,'#regenerateButton');assert.notEqual(await page.locator('#draftCopy').inputValue(),templateBefore);assert.deepEqual(errors,[]);await context.close();console.log('PASS: malformed startup/import, post-commit response loss retry, failed version save retry, concurrent edit conflict, independent tab drafts, and synthetic workspace isolation.');
 const offline=await browser.newPage();await offline.route('**/offline-preview',route=>route.fulfill({contentType:'text/html',body:require('node:fs').readFileSync('marketing-agent-demo.html','utf8')}));await offline.goto(process.env.APP_URL+'/offline-preview');await settled(offline);assert.match(await offline.locator('#serviceStatus').textContent(),/Offline preview/);await offline.waitForFunction(()=>document.querySelector('#assetSelect').options.length===10);assert.equal(await offline.locator('#libraryCount').textContent(),'1');console.log('PASS: labeled standalone offline campaign demo.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
