const steps = [
  {category:'01 / PROBLEM',title:'AI assistance becomes risky when decisions disappear inside automation.',explanation:'Executives need help triaging information and preparing work, but they still need to know what changed, what evidence was used, and whether anything left the workspace.',talk:'“I designed Orbit around the decision boundary first. The model can prepare work, but the owner remains responsible for review and execution.”',badge:'Product framing',screenTitle:'Prepare → review → decide',example:'Orbit keeps the request, editable draft, approval state, and simulated outcome together instead of hiding them behind a chat response.',proof:['Fictional Personal and Work workspaces','Prepared actions remain visible','No automatic approval or sending']},
  {category:'02 / EXPERIENCE',title:'One workspace turns scattered requests into a focused decision queue.',explanation:'The interface combines a briefing, inbox, calendar, tasks, approvals, and campaign work while preserving separate Personal and Work state.',talk:'“The product is intentionally broader than a chatbot. It shows what needs attention, what Orbit already prepared, and exactly where my decision is required.”',badge:'Usable workflow',screenTitle:'Executive Assistant front door',example:'Personal: life, family, bills, and appointments.\nWork: messages, meetings, projects, documents, and campaigns.',proof:['Persistent Light, Dark, and Auto themes','Responsive desktop and mobile layout','Explicit workspace switching and reset scope']},
  {category:'03 / GENERATION',title:'Scripted by default. AI is optional, explicit, and replaceable.',explanation:'Scripted mode works with no account or API key. Local Ollama and hosted Ollama Cloud use the same server-side generation boundary only after explicit configuration and user selection.',talk:'“I treated the model as an optional provider, not the application architecture. The workflow still functions when AI is unavailable.”',badge:'Provider boundary',screenTitle:'Three modes, one editor',example:'Scripted demo → default and cost-free\nLocal AI → optional loopback provider\nCloud AI → optional backend-authenticated provider',proof:['No provider is selected silently','Credentials never enter browser storage','Provider failures preserve the current draft']},
  {category:'04 / GROUNDING',title:'Generated answers must prove what workspace facts support them.',explanation:'Ask Orbit sends a bounded fictional snapshot and accepts only validated structured answers with known fact IDs. Unknown citations, unsupported views, and extra fields fail closed.',talk:'“Prompt instructions are not enough, so I validate the response against facts the application actually supplied.”',badge:'Untrusted output',screenTitle:'Bounded context and citations',example:'Workspace facts → server adapter → structured answer\nKnown evidence IDs only → safe text rendering\ncanExecute: false',proof:['One bounded repair attempt','No tool invocation from model output','Personal and Work facts remain separate']},
  {category:'05 / REVIEW',title:'A generated reply is editable text—not permission to send.',explanation:'Reply generation prepares a draft inside the existing editor. Saving creates a version; sending still requires the owner’s explicit confirmation and remains a demo simulation.',talk:'“Generation and execution are deliberately separate. Even a valid model response cannot approve itself.”',badge:'Human control',screenTitle:'Exact content before action',example:'Generate → edit → save draft → review → confirm\nCancel at any point\nNo real email provider connected',proof:['Cancellation discards late provider results','Stale confirmation is rejected','Duplicate send attempts return the recorded result']},
  {category:'06 / RELIABILITY',title:'Versioning and idempotency protect the workflow when things go wrong.',explanation:'Optimistic concurrency prevents an old tab from overwriting newer work. Approval binds to an immutable version and digest. Receipt reconciliation prevents duplicate execution after persistence failure.',talk:'“The interesting engineering is in the failure paths: stale data, partial persistence, retries, and duplicate actions.”',badge:'Failure design',screenTitle:'Safe state transitions',example:'Version 2 approved\nVersion 3 saved → approval invalidated\nRetry after receipt-save failure → no second execution',proof:['Restart-safe JSON history','Browser draft recovery','Approval expiry and workspace ownership checks']},
  {category:'07 / EVIDENCE',title:'The claims are backed by tests and observable boundaries.',explanation:'The dependency-free test suite covers workflow state, HTTP boundaries, persistence failures, reply generation, grounded answers, provider errors, workspace separation, and approval safeguards.',talk:'“I can point from each product claim to a test, a browser check, or an explicit limitation in the documentation.”',badge:'Verified locally',screenTitle:'Current V1.7 evidence',example:'104 automated tests passing\nDemo result: simulated: true\nExternal actions: 0\nLight/Dark contrast and mobile reply flow checked',proof:['Mocked Local and Cloud provider tests','Timeout, cancellation, and redaction coverage','No live inference required for regression testing']},
  {category:'08 / VIABILITY',title:'The pattern is viable; the business still needs discovery and production infrastructure.',explanation:'A review-first assistant could be useful for executive operations or other high-accountability workflows. Profitability cannot be claimed without customer interviews, pricing tests, operating-cost data, and measured outcomes.',talk:'“I know the difference between a strong prototype and a business. My next product step would be discovery with a narrow user segment—not connecting real accounts prematurely.”',badge:'Next decision',screenTitle:'What would make it sellable?',example:'Choose one buyer and urgent workflow\nValidate willingness to pay\nAdd identity, integrations, storage, and audit controls\nMeasure time saved and decision quality',proof:['No fabricated customer or impact claims','Production gaps are documented','Provider costs remain optional and controlled']}
];

const byId=id=>document.getElementById(id);
const elements={category:byId('category'),title:byId('title'),explanation:byId('explanation'),talk:byId('talk'),badge:byId('badge'),stepNumber:byId('step-number'),screenTitle:byId('screen-title'),example:byId('example'),proof:byId('proof-list'),progress:byId('progress'),progressBar:byId('progress-bar'),back:byId('back'),next:byId('next')};
const initialStep=Number.parseInt(location.hash.replace('#step-',''),10);
let index=Number.isInteger(initialStep)&&initialStep>=1&&initialStep<=steps.length?initialStep-1:0;

function render(focus=false){
  const step=steps[index];
  elements.category.textContent=step.category;elements.title.textContent=step.title;elements.explanation.textContent=step.explanation;elements.talk.textContent=step.talk;elements.badge.textContent=step.badge;elements.stepNumber.textContent=String(index+1).padStart(2,'0');elements.screenTitle.textContent=step.screenTitle;elements.example.textContent=step.example;
  elements.proof.replaceChildren(...step.proof.map(item=>{const li=document.createElement('li');li.textContent=item;return li;}));
  elements.progress.textContent=`${index+1} of ${steps.length}`;elements.progressBar.style.width=`${((index+1)/steps.length)*100}%`;elements.back.disabled=index===0;elements.next.disabled=index===steps.length-1;history.replaceState(null,'',`#step-${index+1}`);
  if(focus)elements.title.focus({preventScroll:true});
}
function move(direction){const nextIndex=Math.min(steps.length-1,Math.max(0,index+direction));if(nextIndex===index)return;index=nextIndex;render(true);}
elements.back.addEventListener('click',()=>move(-1));elements.next.addEventListener('click',()=>move(1));
document.addEventListener('keydown',event=>{const targetIsInteractive=event.target instanceof Element&&event.target.closest('button,a,input,select,textarea');if(event.altKey||event.ctrlKey||event.metaKey||targetIsInteractive)return;if(event.key==='ArrowLeft'){event.preventDefault();move(-1);}if(event.key==='ArrowRight'){event.preventDefault();move(1);}if(event.key==='Home'){event.preventDefault();index=0;render(true);}if(event.key==='End'){event.preventDefault();index=steps.length-1;render(true);}});
render();
