const steps = [
  ['01 / REQUEST','Keep the brief with the work.','A structured campaign brief records the business, audience, platform, tone, and goal. The current generator returns fixed fictional sample assets, not personalized AI content.','Say: “The brief stays attached to the workflow, so the reviewer can see the original intent.”','Fictional brief','Campaign request','Business: Maple Paws dog training\nAudience: Local dog owners\nPlatform: Instagram · Tone: Friendly\nGoal: Encourage class enquiries'],
  ['02 / EDIT','Make the draft worth reviewing.','An owner edits the sample content and saves a new frozen version. Browser scratch recovery is separate from the authoritative server record.','Say: “Unsaved edits are recoverable, but they cannot silently become approved content.”','Illustrative saved version 2','Owner-edited launch post','New to dog training? Maple Paws is planning a beginner class for local dog owners. Ask us about the next session.\n\nFictional business. Illustrative owner-written copy.'],
  ['03 / PROTECT','A stale tab cannot overwrite newer work.','Saving requires the version the editor started from. If someone has saved a newer version, the server rejects the stale save and keeps the newer content.','Say: “I used optimistic concurrency to prevent lost updates rather than relying only on the interface.”','Illustrative conflict','Two-tab safety check','Tab A opened version 1\nTab B saved version 2\nTab A tries to save against version 1\nResult: rejected; version 2 is preserved'],
  ['04 / APPROVE','Approve the version—not just the request.','Approval identifies the frozen draft and its digest. A later revision invalidates earlier approval; validation also rejects empty assets.','Say: “The approval belongs to exactly what the person reviewed.”','Illustrative approval','Version-specific review','Saved version 2 → approved\nNew edit saved as version 3 → review required again\nUnsaved scratch → never eligible for execution'],
  ['05 / EXPORT','Take away only reviewed content.','Copy or download exports the current reviewed saved version with its request, assets, version, and sample-content disclaimer. This does not publish.','Say: “The export preserves provenance and avoids accidentally sharing an unreviewed edit.”','Local-only output','Reviewed draft.txt','Request + campaign brief\nLaunch post + video script + calendar\nSaved version + preview disclaimer\nNo social account or external publishing call'],
  ['06 / RECEIPT','Finish once. Keep the history.','Simulated execution records an idempotent receipt. Local history survives restarts, and reconciliation prevents a duplicate after a persistence failure.','Say: “This is a workflow engineering prototype. Live AI, authentication, and production integrations are future work.”','Simulation, not a real send','Engineering evidence','Run npm test for current regression results; see VERIFICATION.md for recorded evidence\nCoverage: workflow, HTTP, persistence, recovery, export, showcase assets, executive replies, Personal/Work separation, legacy Marketing safety\nTargeted keyboard and phone-width checks\nNo real customers or measured business-impact claims']
];
let index=0;
const el=id=>document.getElementById(id);
function render(focus=false){const s=steps[index];['category','title','explanation','talk','badge','screen-title','example'].forEach((id,i)=>el(id).textContent=s[i]);el('progress').textContent=`${index+1} of ${steps.length}`;el('back').disabled=index===0;el('next').disabled=index===steps.length-1;if(focus)el('title').focus();}
el('back').addEventListener('click',()=>{if(index>0){index--;render(true);}});
el('next').addEventListener('click',()=>{if(index<steps.length-1){index++;render(true);}});
render();
