const test=require('node:test'),assert=require('node:assert/strict');
const core=require('../reply/core.js'),fixtures=require('../reply/fixtures.js');
function setup(){let tick='2026-10-08T12:00:00.000Z',sequence=0;const repository=core.memoryRepository(),executor=core.demoExecutor();const service=core.createService({repository,messages:Object.values(fixtures).flat(),executor,clock:()=>tick,id:()=>`id-${++sequence}`});const context={workspace:{id:'work'},actor:{id:'demo-dave'},messageId:'work-message-0'};return {repository,executor,service,context,time:v=>tick=v};}
const value=result=>{assert.equal(result.ok,true,JSON.stringify(result));return result.value;};
function draft(x){return value(x.service.createReplyDraft({...x.context}));}
function authorize(x,d){const review=value(x.service.requestReplyReview({...x.context,draftId:d.draft.id,versionId:d.version.id})).review;return value(x.service.approveReplyVersion({...x.context,draftId:d.draft.id,reviewId:review.id})).approval;}
function execute(x,d,a){return x.service.executeApprovedReply({...x.context,draftId:d.draft.id,approvalId:a.id});}
test('loads fictional message without DOM',()=>{const x=setup();assert.equal(value(x.service.loadMessage(x.context)).sender,'Sarah Mitchell');assert.equal(typeof document,'undefined');});
test('unknown message, malformed input and wrong workspace return structured errors',()=>{const x=setup();assert.equal(x.service.loadMessage({}).error.code,'INVALID_INPUT');assert.equal(x.service.loadMessage({...x.context,messageId:'missing'}).error.code,'MESSAGE_NOT_FOUND');assert.equal(x.service.loadMessage({...x.context,workspace:{id:'personal'}}).error.code,'WORKSPACE_MISMATCH');});
test('stable draft ID and immutable numbered versions with original settings',()=>{const x=setup(),d=draft(x);const saved=value(x.service.saveReplyDraftVersion({...x.context,draftId:d.draft.id,expectedRevision:1,body:'Revised',brief:'Keep scope clear',settings:{goal:'clarify',tone:'warm',feedback:'mixed'}}));assert.equal(saved.draft.id,d.draft.id);assert.equal(saved.version.revision,2);assert.notEqual(saved.version.id,d.version.id);d.version.body='Caller tampering';const history=value(x.service.getReplyHistory(x.context));assert.notEqual(history.versions[0].body,'Caller tampering');assert.equal(history.versions[1].brief,'Keep scope clear');assert.equal(history.versions[1].settings.tone,'warm');});
test('stale draft revision is rejected without writing',()=>{const x=setup(),d=draft(x),before=x.repository.read();assert.equal(x.service.reviseReplyDraft({...x.context,draftId:d.draft.id,expectedRevision:0,body:'Bad'}).error.code,'STALE_REVISION');assert.deepEqual(x.repository.read(),before);});
test('review and approval bind exactly to current immutable version',()=>{const x=setup(),d=draft(x),a=authorize(x,d);assert.equal(a.versionId,d.version.id);assert.equal(a.revision,1);assert.equal(a.messageId,x.context.messageId);});
test('unapproved execution is rejected',()=>{const x=setup(),d=draft(x);assert.equal(execute(x,d,{id:'missing'}).error.code,'APPROVAL_REQUIRED');assert.equal(x.executor.calls,0);});
test('revision invalidates prior approval and old review cannot reapprove',()=>{const x=setup(),d=draft(x),a=authorize(x,d);const review=value(x.service.getReplyHistory(x.context)).reviews[0];value(x.service.reviseReplyDraft({...x.context,draftId:d.draft.id,expectedRevision:1,body:'Changed after approval'}));assert.equal(execute(x,d,a).error.code,'APPROVAL_STALE');assert.equal(x.service.approveReplyVersion({...x.context,draftId:d.draft.id,reviewId:review.id}).error.code,'APPROVAL_STALE');assert.equal(x.executor.calls,0);});
test('expired approval cannot execute',()=>{const x=setup(),d=draft(x),a=authorize(x,d);x.time('2026-10-08T12:11:00.000Z');assert.equal(execute(x,d,a).error.code,'APPROVAL_STALE');});
test('approved version executes once and duplicate returns original execution',()=>{const x=setup(),d=draft(x),a=authorize(x,d),sent=value(execute(x,d,a));assert(sent.execution.simulated);assert.equal(sent.execution.payload.body,d.version.body);const again=execute(x,d,a);assert.equal(again.error.code,'ALREADY_EXECUTED');assert.equal(again.error.details.execution.id,sent.execution.id);assert.equal(x.executor.calls,1);const h=value(x.service.getReplyHistory(x.context));assert.equal(h.executions.length,1);assert.equal(h.activity.filter(e=>e.kind==='reply.executed').length,1);});
test('wrong actor/workspace cannot operate on draft',()=>{const x=setup(),d=draft(x);assert.equal(x.service.requestReplyReview({...x.context,actor:{id:'other'},draftId:d.draft.id,versionId:d.version.id}).error.code,'WORKSPACE_MISMATCH');assert.equal(x.service.requestReplyReview({...x.context,workspace:{id:'personal'},draftId:d.draft.id,versionId:d.version.id}).error.code,'WORKSPACE_MISMATCH');});
test('invalid body/settings/headers do not change repository',()=>{const x=setup(),d=draft(x),before=x.repository.read();for(const fields of [{body:''},{body:'Okay',settings:{tone:'bad'}},{body:'Okay',subject:'Header\nBcc: injected@example.com'}])assert.equal(x.service.reviseReplyDraft({...x.context,draftId:d.draft.id,expectedRevision:1,...fields}).error.code,'INVALID_INPUT');assert.deepEqual(x.repository.read(),before);});
test('repository read/write failures return PERSISTENCE_FAILED',()=>{for(const fail of ['read','write']){const repository=core.memoryRepository();repository[fail]=()=>{throw Error('disk')};const service=core.createService({repository,messages:fixtures.work});const result=service.createReplyDraft({workspace:{id:'work'},actor:{id:'dave'},messageId:'work-message-0'});assert.equal(result.error.code,'PERSISTENCE_FAILED');assert.equal(result.error.retryable,true);}});
test('simulated adapter failure creates no execution; approved retry succeeds',()=>{const x=setup(),d=draft(x),a=authorize(x,d);x.executor.failNext();assert.equal(execute(x,d,a).error.code,'EXECUTION_FAILED');assert.equal(value(x.service.getReplyHistory(x.context)).executions.length,0);assert.equal(value(execute(x,d,a)).execution.status,'Sent');assert.equal(x.executor.calls,1);});
test('receipt persistence failure can retry without a second adapter send',()=>{const x=setup(),d=draft(x),a=authorize(x,d),write=x.repository.write;let fail=true;x.repository.write=data=>{if(fail)throw Error('disk');return write(data)};const result=execute(x,d,a);assert.equal(result.error.code,'PERSISTENCE_FAILED');assert.equal(result.error.details.phase,'receipt-not-persisted');assert.equal(x.executor.calls,1);fail=false;value(execute(x,d,a));assert.equal(x.executor.calls,1);assert.equal(value(x.service.getReplyHistory(x.context)).executions.length,1);});
test('repository snapshot restores versions, approvals, executions and events',()=>{const x=setup(),d=draft(x),a=authorize(x,d);value(execute(x,d,a));const service=core.createService({repository:core.memoryRepository(x.repository.read()),messages:fixtures.work});const h=value(service.getReplyHistory(x.context));assert.equal(h.versions.length,1);assert.equal(h.approvals.length,1);assert.equal(h.executions.length,1);assert(h.activity.length>=4);});
test('alternatives generated by core differ and honor goal/tone/feedback',()=>{const x=setup(),d=draft(x);const input={...x.context,draftId:d.draft.id,expectedRevision:1,brief:'Scope unclear',settings:{goal:'decline',tone:'warm',feedback:'negative'}};const one=value(x.service.prepareReplyAlternative(input));const two=value(x.service.prepareReplyAlternative({...input,expectedRevision:one.draft.currentRevision}));assert.notEqual(one.version.body,two.version.body);assert(one.version.body.includes('concerns'));assert(one.version.body.includes('will not proceed'));assert(one.version.body.includes('Dave'));});
test('adapter refuses an unapproved version',()=>{const x=setup(),d=draft(x);assert.throws(()=>x.executor.execute({version:d.version,approval:null,idempotencyKey:'bad',now:'2026-10-08T12:00:00Z'}));assert.equal(x.executor.calls,0);});
test('corrupt nested repository records fail closed without being overwritten',()=>{
 const x=setup(),d=draft(x);authorize(x,d);const original=x.repository.read();
 for(const corrupt of [s=>s.drafts[0].versions[0].workspaceId='other',s=>s.approvals[0].expiresAt='invalid',s=>s.approvals[0].versionId='missing',s=>s.drafts.push(s.drafts[0])]){
  const snapshot=structuredClone(original);corrupt(snapshot);let writes=0;
  const service=core.createService({messages:fixtures.work,repository:{read:()=>snapshot,write:()=>{writes++;}}});
  assert.equal(service.getReplyHistory(x.context).error.code,'PERSISTENCE_FAILED');assert.equal(writes,0);
 }
});
test('approval expires at its exact deadline',()=>{const x=setup(),d=draft(x),a=authorize(x,d);x.time(a.expiresAt);assert.equal(execute(x,d,a).error.code,'APPROVAL_STALE');assert.equal(x.executor.calls,0);});
test('malformed execution receipt is rejected without recording success',()=>{
 const x=setup(),d=draft(x),a=authorize(x,d);
 const service=core.createService({messages:fixtures.work,repository:x.repository,clock:()=> '2026-10-08T12:00:00.000Z',executor:{execute:()=>({status:'Sent',simulated:true})}});
 assert.equal(service.executeApprovedReply({...x.context,draftId:d.draft.id,approvalId:a.id}).error.code,'EXECUTION_FAILED');assert.equal(value(x.service.getReplyHistory(x.context)).executions.length,0);
});
