import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {CampaignService} from '../src/application/campaign-service.js';
import {SqliteRepository} from '../src/infrastructure/sqlite-repository.js';
import {TemplateContentGenerator} from '../src/content/template-generator.js';
import {briefDefaults,profileDefaults} from '../src/domain/validation.js';
import type {ActorContext,ServiceResult,Campaign} from '../src/domain/contracts.js';
const alice:ActorContext={actor:{id:'actor-alice',name:'Alice'},workspaceId:'workspace-alice'};
const bob:ActorContext={actor:{id:'actor-bob',name:'Bob'},workspaceId:'workspace-bob'};
const input={kind:'campaign',brief:{...briefDefaults,topic:'Gentle first grooms for puppies.'},profile:profileDefaults,variant:0};
function value<T>(result:ServiceResult<T>):T {if(!result.ok)assert.fail(JSON.stringify(result));return result.value;}
function error(result:ServiceResult<unknown>,code:string){assert.equal(result.ok,false);if(!result.ok)assert.equal(result.error.code,code);}
function fixture(t:test.TestContext,path=':memory:'){let fail=false;const repo=new SqliteRepository(path,()=>{if(fail)throw new Error('injected commit failure');});const service=new CampaignService(repo,new TemplateContentGenerator());t.after(()=>repo.close());return {repo,service,fail:(enabled:boolean)=>fail=enabled,create:()=>value(service.createCampaign(alice,input,'create'))};}
function version(c:Campaign,copy='Edited copy'){return {campaignId:c.id,expectedRevision:c.revision,assets:{message:copy},variant:0,label:'Edited'};}
test('campaign creation generates deterministic content with explicit ownership and unique IDs',t=>{const f=fixture(t);const c=f.create();assert.equal(c.workspaceId,alice.workspaceId);assert.equal(c.createdBy,alice.actor.id);assert.equal(c.revision,1);assert.equal(Object.keys(c.versions[0]!.assets).length,10);assert.equal(c.versions[0]!.revision,1);assert.deepEqual(value(f.service.getCampaign(alice,c.id)),c);const second=value(f.service.createCampaign(alice,input,'different'));assert.notEqual(c.id,second.id);assert.notEqual(c.versions[0]!.id,second.versions[0]!.id);});
test('versions append atomically and duplicate content does not create another snapshot',t=>{const f=fixture(t),c=f.create();const saved=value(f.service.saveCampaignVersion(alice,version(c),'version'));assert.equal(saved.revision,2);assert.equal(saved.versions.length,2);const same=value(f.service.saveCampaignVersion(alice,version(saved),'same-content'));assert.equal(same.revision,2);assert.equal(same.versions.length,2);});
test('campaign and version retries replay committed response; key reuse with changed input is denied',t=>{const f=fixture(t),c=f.create();assert.deepEqual(value(f.service.createCampaign(alice,input,'create')),c);const request=version(c);const saved=value(f.service.saveCampaignVersion(alice,request,'version'));assert.deepEqual(value(f.service.saveCampaignVersion(alice,request,'version')),saved);assert.equal(value(f.service.listCampaigns(alice)).length,1);assert.equal(value(f.service.getCampaign(alice,c.id)).versions.length,2);error(f.service.saveCampaignVersion(alice,{...request,label:'different'},'version'),'IDEMPOTENCY_CONFLICT');});
test('invalid structured inputs and invalid dates are rejected without database changes',t=>{const f=fixture(t);for(const bad of [null,{}, {...input,actor:alice.actor},{...input,brief:{...input.brief,deadline:'2026-99-99'}},{...input,variant:2}])error(f.service.createCampaign(alice,bad,'bad'),'VALIDATION_ERROR');assert.equal(value(f.service.listCampaigns(alice)).length,0);});
test('failed creation commits neither campaign, version, nor idempotency response; retry succeeds',t=>{const f=fixture(t);f.fail(true);error(f.service.createCampaign(alice,input,'create'),'PERSISTENCE_ERROR');assert.equal(f.repo.db.prepare('SELECT count(*) n FROM campaigns').get()!.n,0);assert.equal(f.repo.db.prepare('SELECT count(*) n FROM versions').get()!.n,0);assert.equal(f.repo.db.prepare('SELECT count(*) n FROM idempotency').get()!.n,0);f.fail(false);assert.equal(f.create().versions.length,1);});
test('failed version save never claims saved; retry persists once after rollback',t=>{const f=fixture(t),c=f.create();f.fail(true);error(f.service.saveCampaignVersion(alice,version(c),'version'),'PERSISTENCE_ERROR');f.fail(false);assert.deepEqual(value(f.service.getCampaign(alice,c.id)),c);const saved=value(f.service.saveCampaignVersion(alice,version(c),'version'));assert.equal(saved.versions.length,2);assert.equal(saved.revision,2);assert.deepEqual(value(f.service.saveCampaignVersion(alice,version(c),'version')),saved);});
test('cross-workspace reads, writes, archive and imports are denied',t=>{const f=fixture(t),c=f.create();const intruder={...bob,workspaceId:alice.workspaceId};error(f.service.getCampaign(intruder,c.id),'FORBIDDEN');error(f.service.listCampaigns(intruder),'FORBIDDEN');error(f.service.createCampaign(intruder,input,'steal'),'FORBIDDEN');error(f.service.saveCampaignVersion(intruder,version(c),'steal'),'FORBIDDEN');error(f.service.archiveCampaign(intruder,{campaignId:c.id,expectedRevision:1},'steal'),'FORBIDDEN');error(f.service.importHistory(intruder,{records:[]},'steal'),'FORBIDDEN');error(f.service.getCampaign(bob,c.id),'NOT_FOUND');error(f.service.listCampaigns({...alice,workspaceId:'nonexistent'}),'FORBIDDEN');assert.equal(value(f.service.listCampaigns(bob)).length,0);});
test('concurrent snapshots reject stale revision rather than overwrite committed edits',t=>{const f=fixture(t),first=f.create();const tab2=value(f.service.getCampaign(alice,first.id));const winner=value(f.service.saveCampaignVersion(alice,version(first,'first edit'),'one'));error(f.service.saveCampaignVersion(alice,version(tab2,'second edit'),'two'),'REVISION_CONFLICT');assert.deepEqual(value(f.service.getCampaign(alice,first.id)),winner);});
test('updateCampaignVersion enforces both revisions and rolls back partial version updates',t=>{const f=fixture(t),c=f.create();const request={...version(c),versionId:c.versions[0]!.id,expectedVersionRevision:1};f.fail(true);error(f.service.updateCampaignVersion(alice,request,'update'),'PERSISTENCE_ERROR');f.fail(false);assert.deepEqual(value(f.service.getCampaign(alice,c.id)),c);const updated=value(f.service.updateCampaignVersion(alice,request,'update'));assert.equal(updated.revision,2);assert.equal(updated.versions.length,1);assert.equal(updated.versions[0]!.revision,2);assert.deepEqual(value(f.service.updateCampaignVersion(alice,request,'update')),updated);error(f.service.updateCampaignVersion(alice,{...request,expectedRevision:2},'stale-version'),'REVISION_CONFLICT');});
test('archive and restore are atomic, revision checked, and retry safe without duplicated records',t=>{const f=fixture(t),c=f.create();const archive={campaignId:c.id,expectedRevision:1};f.fail(true);error(f.service.archiveCampaign(alice,archive,'archive'),'PERSISTENCE_ERROR');f.fail(false);assert.equal(value(f.service.getCampaign(alice,c.id)).archived,false);const archived=value(f.service.archiveCampaign(alice,archive,'archive'));assert.equal(archived.revision,2);assert.equal(archived.archived,true);assert.deepEqual(value(f.service.archiveCampaign(alice,archive,'archive')),archived);error(f.service.saveCampaignVersion(alice,version(archived),'editing'),'ARCHIVED');const restore={campaignId:c.id,expectedRevision:2};f.fail(true);error(f.service.restoreCampaign(alice,restore,'restore'),'PERSISTENCE_ERROR');f.fail(false);assert.deepEqual(value(f.service.getCampaign(alice,c.id)),archived);const restored=value(f.service.restoreCampaign(alice,restore,'restore'));assert.equal(restored.archived,false);assert.equal(restored.revision,3);assert.deepEqual(value(f.service.restoreCampaign(alice,restore,'restore')),restored);error(f.service.archiveCampaign(alice,archive,'stale'),'REVISION_CONFLICT');assert.equal(value(f.service.listCampaigns(alice)).length,1);});
test('malformed imports report per-record failures, preserve stable IDs and journal every original',t=>{const f=fixture(t);const records=[{id:'legacy-one',tool:'pack',topic:'Old campaign',copy:'Original',date:'2026-10-01T12:00:00Z'},null,{tool:'social',topic:'Bad versions',copy:'Bad',versions:null},{tool:'campaign',topic:'Unknown extra fields',copy:'Extra preserved',extra:{valuable:true}},{tool:'social',topic:'Bad assets',copy:'Bad',assets:{message:null}}];const report=value(f.service.importHistory(alice,{records},'import'));assert.equal(report.imported.length,2);assert.equal(report.rejected.length,3);assert.ok(report.imported.includes('legacy-one'));assert.equal(value(f.service.getCampaign(alice,'legacy-one')).legacyId,'legacy-one');assert.deepEqual(JSON.parse(String(f.repo.db.prepare('SELECT raw FROM imports WHERE id=?').get(report.batchId)!.raw)),records);const repeated=value(f.service.importHistory(alice,{records},'new-import-key'));assert.equal(repeated.imported.length,0);assert.equal(repeated.unchanged.length,2);assert.equal(repeated.rejected.length,3);error(f.service.importHistory(alice,{records:{}},'bad-root'),'VALIDATION_ERROR');const collision=value(f.service.importHistory(alice,{records:[{...records[0],copy:'Changed'}]},'collision'));assert.equal(collision.rejected[0]!.error.code,'ID_CONFLICT');assert.equal(value(f.service.getCampaign(alice,'legacy-one')).versions[0]!.assets.message,'Original');});
test('import write failure rolls back whole batch and retains retry ability',t=>{const f=fixture(t),records=[{tool:'social',topic:'Old campaign',copy:'Original'}];f.fail(true);error(f.service.importHistory(alice,{records},'import'),'PERSISTENCE_ERROR');assert.equal(f.repo.db.prepare('SELECT count(*) n FROM imports').get()!.n,0);assert.equal(f.repo.db.prepare('SELECT count(*) n FROM import_records').get()!.n,0);f.fail(false);assert.equal(value(f.service.listCampaigns(alice)).length,0);assert.equal(value(f.service.importHistory(alice,{records},'import')).imported.length,1);});
test('separate repository connections see durable commits and reject competing revisions',t=>{const dir=mkdtempSync(join(process.cwd(),'.cache/test-db-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));const path=join(dir,'campaigns.sqlite');const f=fixture(t,path),c=f.create();const second=new SqliteRepository(path);t.after(()=>second.close());const service=new CampaignService(second,new TemplateContentGenerator());const stale=value(service.getCampaign(alice,c.id));const saved=value(f.service.saveCampaignVersion(alice,version(c,'committed'),'one'));error(service.saveCampaignVersion(alice,version(stale,'other connection'),'two'),'REVISION_CONFLICT');assert.deepEqual(value(service.getCampaign(alice,c.id)),saved);second.close();const reopened=new SqliteRepository(path);assert.deepEqual(value(new CampaignService(reopened,new TemplateContentGenerator()).getCampaign(alice,c.id)),saved);reopened.close();});
test('migration preserves version identifiers and archived state; duplicate version IDs are rejected',t=>{const f=fixture(t);const record={id:'archived-campaign',tool:'social',topic:'Archived legacy draft',copy:'Saved text',archived:true,versions:[{id:'stable-version',copy:'Saved text'}]};const report=value(f.service.importHistory(alice,{records:[record]},'archived'));assert.equal(report.imported.length,1);const imported=value(f.service.getCampaign(alice,record.id));assert.equal(imported.archived,true);assert.equal(imported.versions[0]!.id,'stable-version');assert.equal(value(f.service.restoreCampaign(alice,{campaignId:record.id,expectedRevision:1},'restore')).archived,false);const collision=value(f.service.importHistory(alice,{records:[{...record,id:'other-campaign'}]},'version-collision'));assert.equal(collision.rejected[0]!.error.code,'ID_CONFLICT');const malformed=value(f.service.importHistory(alice,{records:[{...record,id:'invalid-flag',archived:'true'}]},'invalid-flag'));assert.equal(malformed.rejected[0]!.error.code,'VALIDATION_ERROR');});
