import test from 'node:test';
import assert from 'node:assert/strict';
import {resolve} from 'node:path';
import type {AddressInfo} from 'node:net';
import {SqliteRepository} from '../src/infrastructure/sqlite-repository.js';
import {CampaignService} from '../src/application/campaign-service.js';
import {TemplateContentGenerator} from '../src/content/template-generator.js';
import {createHttpServer} from '../src/server/http.js';
import {briefDefaults,profileDefaults} from '../src/domain/validation.js';
const input={kind:'social',brief:{...briefDefaults,topic:'Saturday appointments are available.'},profile:profileDefaults,variant:0};
async function fixture(t:test.TestContext){const repo=new SqliteRepository(':memory:');const server=createHttpServer(repo,new CampaignService(repo,new TemplateContentGenerator()),resolve('dist'));await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));t.after(async()=>{await new Promise<void>(r=>server.close(()=>r()));repo.close();});const base=`http://127.0.0.1:${(server.address() as AddressInfo).port}`;const request=(path:string,cookie='',data?:unknown,headers:Record<string,string>={})=>fetch(base+path,{method:data===undefined?'GET':'POST',headers:{...(cookie?{Cookie:cookie}:{}),...(data===undefined?{}:{'Content-Type':'application/json','X-Campaign-Client':'1'}),...headers},...(data===undefined?{}:{body:JSON.stringify(data)})});async function login(name:string){const response=await request('/api/session','',{username:name,password:`local-${name}`});assert.equal(response.status,200);assert.match(response.headers.get('set-cookie')!,/HttpOnly; SameSite=Strict/);return response.headers.get('set-cookie')!.split(';')[0]!;}return {repo,request,login};}
test('HTTP requires an opaque valid session; rejects wrong passwords and expired sessions',async t=>{const f=await fixture(t);assert.equal((await f.request('/api/campaigns?workspaceId=workspace-alice')).status,401);assert.equal((await f.request('/api/session','campaign_session=actor-alice')).status,401);assert.equal((await f.request('/api/session','',{username:'alice',password:'wrong'})).status,401);const cookie=await f.login('alice');assert.equal((await f.request('/api/session',cookie)).status,200);f.repo.db.exec('UPDATE sessions SET expires=0');assert.equal((await f.request('/api/session',cookie)).status,401);});
test('HTTP binds actor to session and validates client workspace; no actor spoofing',async t=>{const f=await fixture(t),alice=await f.login('alice'),bob=await f.login('bob');const request={workspaceId:'workspace-alice',input,idempotencyKey:'create'};const created=await (await f.request('/api/campaigns/create',alice,request)).json();assert.equal(created.ok,true);assert.equal(created.value.createdBy,'actor-alice');assert.equal((await f.request('/api/campaigns?workspaceId=workspace-alice',bob)).status,403);assert.equal((await f.request('/api/campaigns/create',bob,request)).status,403);assert.equal((await f.request('/api/campaigns/create',bob,{...request,actor:{id:'actor-alice'}})).status,422);assert.equal((await f.request('/api/campaigns/get?workspaceId=workspace-bob&campaignId='+created.value.id,bob)).status,404);assert.equal((await f.request('/api/campaigns?workspaceId=../alice',alice)).status,422);});
test('HTTP rejects cross-origin writes and exposes typed errors and idempotent responses',async t=>{const f=await fixture(t),cookie=await f.login('alice');const request={workspaceId:'workspace-alice',input,idempotencyKey:'create'};assert.equal((await f.request('/api/campaigns/create',cookie,request,{Origin:'https://untrusted.example'})).status,403);assert.equal((await f.request('/api/campaigns/create',cookie,request,{'X-Campaign-Client':''})).status,403);const first=await (await f.request('/api/campaigns/create',cookie,request)).json();const retry=await (await f.request('/api/campaigns/create',cookie,request)).json();assert.deepEqual(retry,first);const version={workspaceId:'workspace-alice',idempotencyKey:'edit-1',input:{campaignId:first.value.id,expectedRevision:1,assets:{message:'One tab'},variant:0,label:'Edited'}};const replies=await Promise.all([f.request('/api/campaigns/saveVersion',cookie,version),f.request('/api/campaigns/saveVersion',cookie,{...version,idempotencyKey:'edit-2',input:{...version.input,assets:{message:'Another tab'}}})]);assert.deepEqual(replies.map(r=>r.status).sort(),[200,409]);const conflict=await replies.find(r=>r.status===409)!.json();assert.equal(conflict.error.code,'REVISION_CONFLICT');});
